-- Jalankan seluruh SQL ini di Supabase SQL Editor.
-- Database: 1 baris = 1 habit pada 1 tanggal untuk 1 user.

create table if not exists public.habit_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  habit_id text not null,
  status smallint not null check (status between 0 and 2),
  note text default '',
  created_at timestamptz not null default now(),
  unique (user_id, date, habit_id)
);

alter table public.habit_days enable row level security;

drop policy if exists "Users can view own habit data" on public.habit_days;
create policy "Users can view own habit data"
on public.habit_days
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own habit data" on public.habit_days;
create policy "Users can insert own habit data"
on public.habit_days
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own habit data" on public.habit_days;
create policy "Users can update own habit data"
on public.habit_days
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habit data" on public.habit_days;
create policy "Users can delete own habit data"
on public.habit_days
for delete
to authenticated
using (auth.uid() = user_id);
